<?php

namespace ContainerYGTzDDq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_ErrorListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.error_listener' shared service.
     *
     * @return \Symfony\Component\Console\EventListener\ErrorListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/EventListener/ErrorListener.php';

        $a = new \Symfony\Bridge\Monolog\Logger('console');
        $a->pushProcessor(($container->privates['Monolog\\Processor\\PsrLogMessageProcessor'] ?? ($container->privates['Monolog\\Processor\\PsrLogMessageProcessor'] = new \Monolog\Processor\PsrLogMessageProcessor())));
        $a->pushProcessor(($container->privates['Monolog\\Processor\\WebProcessor'] ?? ($container->privates['Monolog\\Processor\\WebProcessor'] = new \Monolog\Processor\WebProcessor())));
        $a->pushProcessor(($container->privates['Monolog\\Processor\\MemoryUsageProcessor'] ?? ($container->privates['Monolog\\Processor\\MemoryUsageProcessor'] = new \Monolog\Processor\MemoryUsageProcessor())));
        $a->pushHandler(($container->privates['monolog.handler.main'] ?? $container->getMonolog_Handler_MainService()));

        return $container->privates['console.error_listener'] = new \Symfony\Component\Console\EventListener\ErrorListener($a);
    }
}
