<?php

namespace ContainerSXI9Dbs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hhi6i07Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hhi6i07' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hhi6i07'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'httpClient' => ['privates', 'app.http.client', 'getApp_Http_ClientService', true],
            'ipApi' => ['privates', 'App\\Model\\IpApiProvider', 'getIpApiProviderService', true],
        ], [
            'httpClient' => '?',
            'ipApi' => '?',
        ]);
    }
}
