<?php

namespace ContainerRK3MBfV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIpApiProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Model\IpApiProvider' shared autowired service.
     *
     * @return \App\Model\IpApiProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Model/Base/AbstractIpProviderModel.php';
        include_once \dirname(__DIR__, 4).'/src/Contract/IpProviderModelInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Model/IpApiProvider.php';
        include_once \dirname(__DIR__, 4).'/src/Model/Factory/IpApiProviderFactory.php';

        return $container->privates['App\\Model\\IpApiProvider'] = \App\Model\Factory\IpApiProviderFactory::create($container->parameters['ip_api']);
    }
}
