<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYGTzDDq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYGTzDDq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYGTzDDq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYGTzDDq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYGTzDDq\App_KernelDevDebugContainer([
    'container.build_hash' => 'YGTzDDq',
    'container.build_id' => 'baeccfb4',
    'container.build_time' => 1595321425,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYGTzDDq');
